DROP INDEX IDX_CC_INTERACTION;

CREATE INDEX IDX_CC_INTERACTION ON CUSTOMER_CARE_FACT
(INTERACTION_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_RESERVATION_FACT_DATE_KEY;

CREATE INDEX IDX_RESERVATION_FACT_DATE_KEY ON RESERVATION_FACT
(DATE_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_RF_AIRCRAFT;

CREATE INDEX IDX_RF_AIRCRAFT ON RESERVATION_FACT
(AIRCRAFT_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_RF_FARE;

CREATE INDEX IDX_RF_FARE ON RESERVATION_FACT
(FARE_BASIS_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_RF_ORIGIN;

CREATE INDEX IDX_RF_ORIGIN ON RESERVATION_FACT
(TRIP_ORIGIN_AIRPORT_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_RF_PASSENGER;

CREATE INDEX IDX_RF_PASSENGER ON RESERVATION_FACT
(PASSENGER_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_ADD;

CREATE INDEX IDX_SFA_ADD ON SEGMENT_FLIGHT_ACTIVITY_FACT
(ACTUAL_DEPARTURE_DATE_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_ADT;

CREATE INDEX IDX_SFA_ADT ON SEGMENT_FLIGHT_ACTIVITY_FACT
(ACTUAL_DEPARTURE_TIME_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_AIRCRAFT;

CREATE INDEX IDX_SFA_AIRCRAFT ON SEGMENT_FLIGHT_ACTIVITY_FACT
(AIRCRAFT_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_COSF;

CREATE INDEX IDX_SFA_COSF ON SEGMENT_FLIGHT_ACTIVITY_FACT
(CLASS_OF_SERVICE_FLOWN_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_DEST;

CREATE INDEX IDX_SFA_DEST ON SEGMENT_FLIGHT_ACTIVITY_FACT
(SEG_DESTINATION_AIRPORT_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_FLIGHT;

CREATE INDEX IDX_SFA_FLIGHT ON SEGMENT_FLIGHT_ACTIVITY_FACT
(FLIGHT_NUMBER)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_PASS;

CREATE INDEX IDX_SFA_PASS ON SEGMENT_FLIGHT_ACTIVITY_FACT
(PASSENGER_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_PP;

CREATE INDEX IDX_SFA_PP ON SEGMENT_FLIGHT_ACTIVITY_FACT
(PASSENGER_PROFILE_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_SDD;

CREATE INDEX IDX_SFA_SDD ON SEGMENT_FLIGHT_ACTIVITY_FACT
(SCHEDULED_DEPARTURE_DATE_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_SDT;

CREATE INDEX IDX_SFA_SDT ON SEGMENT_FLIGHT_ACTIVITY_FACT
(SCHEDULED_DEPARTURE_TIME_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP INDEX IDX_SFA_SOA;

CREATE INDEX IDX_SFA_SOA ON SEGMENT_FLIGHT_ACTIVITY_FACT
(SEG_ORIGIN_AIRPORT_KEY)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
